grid_field_formatter.settings:
  type: config_object
  label: "Setting for Grid Field Formatter module"
  mapping:
    bootstrap:
      type: boolean
       label: Enable Bootstrap compatibility
    field_types:
      type: sequence
      label: List of field types supporting Grid Field Formatter
      sequence:
        - type: string